name:                millisecond08
version:             0.1.0.0
github:              sethetter/millisecond08
license:             BSD3
author:              Seth Etter
maintainer:          sethetter@gmail.com
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sethetter/millisecond08#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split

library:
  source-dirs: src

executables:
  millisecond08-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond08

tests:
  millisecond08-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond08
