name:                millisecond12
version:             0.1.0.0
github:              sethetter/millisecond12
license:             BSD3
author:              Seth Etter
maintainer:          sethetter@gmail.com
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sethetter/millisecond12#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers

library:
  source-dirs: src

executables:
  millisecond12-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond12

tests:
  millisecond12-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond12
