name:                millisecond24
version:             0.1.0.0
github:              "sethetter/millisecond24"
license:             BSD3
author:              "Seth Etter"
maintainer:          "sethetter@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sethetter/millisecond24#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  millisecond24-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond24

tests:
  millisecond24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - millisecond24
